package LeetCode.Java;

/**
 * Created by Vonzpf on 17/3/29.
 */

import java.util.HashMap;

/**-------------------------Title---------------------------------
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<Character, Integer>();
        for (int i = 0; i < s.length(); i++){
            if (!map.containsKey(s.charAt(i)))
                map.put(s.charAt(i), 1);
            else{
                int s_value = map.get(s.charAt(i));
                s_value += 1;
                map.replace(s.charAt(i), s_value);
            }
        }
        for (int j = 0; j < t.length(); j++){
            if (!map.containsKey(t.charAt(j)))
                return t.charAt(j);
            else {
                if (map.get(t.charAt(j)) == 0)
                    return t.charAt(j);
                else{
                    int t_value = map.get(t.charAt(j));
                    t_value -= 1;
                    map.replace(t.charAt(j), t_value);
                }
            }
        }
        return 0;
    }
}
